{% set pkgname = "pv" %}
{% set version = "1.9.7" %}

package:
  name: {{ pkgname }}
  version: {{ version }}

source:
  url: http://www.ivarch.com/programs/sources/{{ pkgname }}-{{ version }}.tar.gz
  sha256: 6976a789ee1bbcfdc47732015b60589c1d0408892252dd7cbb44f43363a2f33a
  # patches:
    #- pv-osx-skip-test.patch  # [osx]

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ stdlib('c') }}

test:
  commands:
    - pv --version

about:
  home: http://www.ivarch.com/programs/pv.shtml
  license: Artistic-2.0
  summary: pv - monitor the progress of data through a pipe

extra:
  recipe-maintainers:
    - martin-g
    - shahin
