{% set pkgname = "pv" %}
{% set version = "1.8.12" %}

package:
  name: {{ pkgname }}
  version: {{ version }}

source:
  url: http://www.ivarch.com/programs/sources/{{ pkgname }}-{{ version }}.tar.gz
  sha256: 9687f9deedb09d0dc00d80c30691f0c91282c0d5d8fa7d6a2a085c8742c2cd7c
  patches:
    - pv-osx-skip-test.patch  # [osx]

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ stdlib('c') }}

test:
  commands:
    - pv --version

about:
  home: http://www.ivarch.com/programs/pv.shtml
  license: Artistic-2.0
  summary: pv - monitor the progress of data through a pipe

extra:
  recipe-maintainers:
    - martin-g
    - shahin
